### ISSUE TITLE
Unity poco ios: ios 上接入Unity的游戏，操作一段时间后（获取元素，点击元素）会出现poco socket 断开的情况

### ISSUE THREAD

**Issue by 1033866383** [AirtestProject/Poco-SDK#106]
问题 mac 系统连接 ios设备，并运行untiy挟带poco的游戏会出现 操作一会（选择元素，选中元素）poco socket就断开的情况。
环境：facebook-wda                       1.4.6
airtest                            1.2.6
pocoui                             1.0.87

报错：Traceback (most recent call last):
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/airtest/cli/runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/pirate/Documents/jenkins_workspace/workspace/saki_auto_test_ios/saki/saki_office_6/saki_office_case_21.air/saki_office_case_21.py", line 46, in {module}
    ocl.enter_office()
  File "/Users/pirate/Documents/jenkins_workspace/workspace/saki_auto_test_ios/saki/saki_common/office_common/office_common.py", line 30, in enter_office
    self.office_button.click()
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/proxy.py", line 613, in get_position
    pos = list(map(float, self.attr('pos')))
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/proxy.py", line 736, in attr
    nodes = self._do_query(multiple=False)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/proxy.py", line 886, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/freezeui/hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/sdk/Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/sdk/Selector.py", line 71, in getRoot
    return self.dumper.getRoot()
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/freezeui/hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/utils/simplerpc/utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/utils/simplerpc/simplerpc.py", line 74, in wait
    self.agent.update()
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/utils/simplerpc/rpcclient.py", line 64, in update
    data = self.conn.recv()
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/utils/simplerpc/transport/tcp/main.py", line 36, in recv
    msg_bytes = self.c.recv()
  File "/Users/pirate/opt/anaconda3/lib/python3.8/site-packages/poco/utils/simplerpc/transport/tcp/safetcp.py", line 39, in recv
    raise socket.error("socket connection broken")
OSError: socket connection broken

**Comment by 1033866383** [comment]
app错误日志：
Sep 22 14:39:32 iPhonex saki_apple(saki_UnityFramework_apple)[30705] <Notice>: Material 'Unlit (Instance)' with Shader 'Live2D Cubism/Unlit' doesn't have a color property '_Color'
Sep 22 14:39:32 iPhonex saki_apple(saki_UnityFramework_apple)[30705] <Notice>: Material 'Unlit (Instance)' with Shader 'Live2D Cubism/Unlit' doesn't have a color property '_Color'
Sep 22 14:39:32 iPhonex saki_apple(saki_UnityFramework_apple)[30705] <Notice>: Material 'Unlit (Instance)' with Shader 'Live2D Cubism/Unlit' doesn't have a color property '_Color'
Sep 22 14:39:32 iPhonex saki_apple(saki_UnityFramework_apple)[30705] <Notice>: Material 'Unlit (Instance)' with Shader 'Live2D Cubism/Unlit' doesn't have a color property '_Color'
Sep 22 14:39:32 iPhonex saki_apple(saki_UnityFramework_apple)[30705] <Notice>: Material 'Unlit (Instance)' with Shader 'Live2D Cubism/Unlit' doesn't have a color property '_Color'
Sep 22 14:39:32 iPhonex kernel[0] <Notice>: saki_apple[30705] Corpse allowed 1 of 5
Sep 22 14:39:32 iPhonex mediaserverd(AudioToolbox)[35] <Notice>:              AQIONode.cpp:592   client <RemoteIOClient@0x1028b6a00(@0x1028b6c70); output; sid:0x4bf67, saki_apple(30705), 'prim'> is NOT Now Playing eligible
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -MXSession- -[MXSession(InternalUse) setCurrentlyPlayingSourceFormatInfo:]: <ID: 3633, CoreSessionID = 13211 Name = sid:0x4bf67, saki_apple(30705), 'prim', Muted = NO, ClientIsPlaying = STOPPED, AudioToolboxIsPlaying = PLAYING, MutePriority = MutePriority_Two, PiP = NO, DoesntActuallyPlayAudio = NO, clientType = 2 Setting CurrentlyPlayingSourceFormatInfo to {
Sep 22 14:39:32 iPhonex mediaserverd(AudioToolbox)[35] <Notice>:  MEDeviceStreamClient.cpp:437   AQME Default-InputOutput: client stopping: <RemoteIOClient@0x1028b6a00(@0x1028b6c70); output; sid:0x4bf67, saki_apple(30705), 'prim'>; running count now 0
Sep 22 14:39:32 iPhonex mediaserverd(AudioToolbox)[35] <Notice>: AudioSession_SubServer.cpp:132   { "action":"client_died", "session":{"ID":"0x4bf67","PID":30705,"name":"saki_apple"}, "details":null }
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -MXSession- -[MXSession(InterfaceImpl) _dealloc]: Deallocating <MXSessionID: 3633, CoreSessionID = 13211 Name = sid:0x4bf67, saki_apple(30705), 'prim', Muted = NO, Playing = YES, MutePriority = MutePriority_Two, PiP = NO, DoesntActuallyPlayAudio = NO, clientType = 2. Current MXSessions count for CoreSession = 0
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -CMSessionMgr- cmsSetIsPlaying: 'sid:0x4bf67, saki_apple(30705), 'prim'' with [SoloAmbientSound/Default] [NonMixable] [System Audio] stopping playing to VirtualAudioDevice_Default. Ringer switch state: Device is silenced, Session is muted. RoutingContextUUID=<private> NowPlayingApp:NO
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -CMSessionMgr- cmsSetIsPlaying: Starting deactivate timer for client 'sid:0x4bf67, saki_apple(30705), 'prim''
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -CMSessionMgr- cmsSetIsActive: 'sid:0x4bf67, saki_apple(30705), 'prim'' with [SoloAmbientSound/Default] [NonMixable] [System Audio] siriEndpointID: (null) going inactive NowPlayingApp:NO
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: [application<com.happyelements.Sakicn>:30705] Workspace connection invalidated.
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: [application<com.happyelements.Sakicn>:30705] Now flagged as pending exit for reason: workspace client connection invalidated
Sep 22 14:39:32 iPhonex kernel[0] <Notice>: necp_process_defunct_list: necp_update_client abort nexus error (2) for pid 30705
Sep 22 14:39:32 iPhonex kernel[0] <Notice>: necp_process_defunct_list: necp_update_client abort nexus error (2) for pid 30705
Sep 22 14:39:32 iPhonex backboardd(IOKit)[19254] <Notice>: Connection removed: IOHIDEventSystemConnection uuid:27C3A028-8496-4EA0-9451-748AA3DB2835 pid:30705 process:saki_apple type:Passive entitlements:0x0 caller:BackBoardServices: <redacted> + 336 attributes:{
    pid = 30705;
Sep 22 14:39:32 iPhonex backboardd(IOKit)[19254] <Notice>: Connection removed: IOHIDEventSystemConnection uuid:649C9E66-47B3-4068-8DAF-9ADE548672C1 pid:30705 process:saki_apple type:Rate Controlled entitlements:0x0 caller:CoreMotion: _ZN16CLMotionActivity15isTypeInVehicleENS_4TypeE + 5848 attributes:{
Sep 22 14:39:32 iPhonex backboardd(BackBoardHIDEventFoundation)[19254] <Notice>: Removing client connection <BKHIDClientConnection: 0x1646bf8f0; IOHIDEventSystemConnectionRef: 0x17141ab70; vpid: 30705(v5BDB6); taskPort: 0x1BAB3A3; bundleID: com.happyelements.Sakicn> for client: IOHIDEventSystemConnection uuid:27C3A028-8496-4EA0-9451-748AA3DB2835 pid:30705 process:saki_apple type:Passive entitlements:0x0 caller:BackBoardServices: <redacted> + 336 attributes:{
    pid = 30705;
Sep 22 14:39:32 iPhonex backboardd(IOKit)[19254] <Notice>: Connection removed: IOHIDEventSystemConnection uuid:2C23CC6F-0AA4-49BE-A97F-7AAA10C84572 pid:30705 process:saki_apple type:Monitor entitlements:0x0 caller:GameController: <redacted> + 132 attributes:(null) state:0x1 events:0 mask:0x0
Sep 22 14:39:32 iPhonex backboardd(BackBoardHIDEventFoundation)[19254] <Error>: invalidated connection pid:30705
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -CMSessionMgr- cmsSetIsActive: Stopping deactivate timer for client 'sid:0x4bf67, saki_apple(30705), 'prim''
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -CMSessionMgr- cmsUpdateMuteStatus: session 'sid:0x4bf67, saki_apple(30705), 'prim'' being unmuted.
Sep 22 14:39:32 iPhonex ReportCrash[30356] <Notice>: Parsing corpse data for pid 30705
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: XPC connection invalidated: [application<com.happyelements.Sakicn>:30705]
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: Invalidating assertion 32-35-515351 (target:[application<com.happyelements.Sakicn>:30705]) from originator [daemon<com.apple.mediaserverd>:35]
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -CMSUtilities- CMSUtility_SendSessionStateAndVolumeReportToAudioStatistics: Stopping reporter for session : sid:0x4bf67, saki_apple(30705), 'prim', reporter id = 150323866956
Sep 22 14:39:32 iPhonex backboardd(BackBoardHIDEventFoundation)[19254] <Notice>: new resolutions for pid:30705 (<display: builtin; environment: keyboardFocus; pid: 30705; token: com.apple.frontboard.systemappservices::sceneID%3Acom.happyelements.Sakicn-default>)
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: [application<com.happyelements.Sakicn>:30705] termination reported by launchd (0, 0, 6)
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: Removing process: [application<com.happyelements.Sakicn>:30705]
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: Removing launch job for: [application<com.happyelements.Sakicn>:30705]
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: Removed job for [application<com.happyelements.Sakicn>:30705]
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: Removing assertions for terminated process: [application<com.happyelements.Sakicn>:30705]
Sep 22 14:39:32 iPhonex powerd[41] <Notice>: Process runningboardd.32 Released SystemIsActive "application<com.happyelements.Sakicn>32-35-515351:MediaExperience.30705."com.happyelements.Sakicn"."SoloAmbientSound".isPlayingProcessAssertion(MediaPlayback)" age:00:03:29  id:51539649231 [System: PrevIdle SysAct]
Sep 22 14:39:32 iPhonex SpringBoard(RunningBoardServices)[19256] <Notice>: Firing exit handlers for 30705 with context <RBSProcessExitContext| voluntary>
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: [application<com.happyelements.Sakicn>:30705] Process exited: <RBSProcessExitContext| voluntary>.
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: [application<com.happyelements.Sakicn>:30705] Setting process task state to: Not Running
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: [application<com.happyelements.Sakicn>:30705] Setting process visibility to: Unknown
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: [application<com.happyelements.Sakicn>:30705] Invalidating workspace.
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: Removing workspace registration for processHandle: [application<com.happyelements.Sakicn>:30705]
Sep 22 14:39:32 iPhonex SpringBoard(FrontBoard)[19256] <Notice>: Removing: <FBApplicationProcess: 0x10652dcb0; application<com.happyelements.Sakicn>:30705(v5BDB6)>
Sep 22 14:39:32 iPhonex SpringBoard(SpringBoard)[19256] <Notice>: Process exited: <FBApplicationProcess: 0x10652dcb0; application<com.happyelements.Sakicn>:30705(v5BDB6)> -> <RBSProcessExitContext| voluntary>
Sep 22 14:39:32 iPhonex runningboardd(RunningBoardServices)[32] <Error>: Unable to get short BSD proc info for 30705: No such process
Sep 22 14:39:32 iPhonex SpringBoard(RunningBoardServices)[19256] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex mediaserverd(RunningBoardServices)[35] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex dasd(RunningBoardServices)[29814] <Notice>: Firing exit handlers for 30705 with context <RBSProcessExitContext| voluntary>
Sep 22 14:39:32 iPhonex mediaserverd(RunningBoardServices)[35] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex mediaserverd(MediaExperience)[35] <Notice>: -CMSessionMgr- CMSessionMgrHandleApplicationStateChange: Client com.happyelements.Sakicn with pid '30705' is now Terminated. Background entitlement: NO ActiveLongFormVideoSession: NO WhitelistedLongFormVideoApp NO
Sep 22 14:39:32 iPhonex SpringBoard(SpringBoard)[19256] <Notice>: didRemoveExternalForegroundApplicationSceneHandle pid:30705 scene:com.apple.frontboard.systemappservices::sceneID%3Acom.happyelements.Sakicn-default now:<empty>
Sep 22 14:39:32 iPhonex SpringBoard(SpringBoard)[19256] <Notice>: rules: target changed from:<pid=30705 token=com.apple.frontboard.systemappservices::sceneID%3Acom.happyelements.Sakicn-default> to (null)
Sep 22 14:39:32 iPhonex SpringBoard(BaseBoard)[19256] <Error>: Unable to get short BSD proc info for 30705: No such process
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Notice>: Acquiring assertion targeting 30705 from originator [daemon<com.apple.SpringBoard>:19256] with description <RBSAssertionDescriptor| "FBSceneSnapshotAction:sceneID:com.happyelements.Sakicn-default" ID:32-19256-515367 target:30705 attributes:[
Sep 22 14:39:32 iPhonex symptomsd(RunningBoardServices)[125] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex dasd(RunningBoardServices)[29814] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex contextstored(RunningBoardServices)[29807] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex watchdogd(RunningBoardServices)[57] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex aggregated(RunningBoardServices)[30405] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex useractivityd(RunningBoardServices)[29803] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex UserEventAgent(RunningBoardServices)[29] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex CommCenter(RunningBoardServices)[91] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex wifid(RunningBoardServices)[51] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex contextstored(RunningBoardServices)[29807] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex aggregated(RunningBoardServices)[30405] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex kbd(RunningBoardServices)[517] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex locationd(RunningBoardServices)[26698] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex dasd(RunningBoardServices)[29814] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex symptomsd(RunningBoardServices)[125] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex testmanagerd(RunningBoardServices)[30673] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex testmanagerd[30673] <Notice>: <XCTestSession: 0x103705530> pid 30675 com.happyelements.Sakicn@/private/var/containers/Bundle/Application/85440B66-599D-43B8-BF2F-1CE9CC086635/saki_apple.app pid: 30705 state: not running
Sep 22 14:39:32 iPhonex testmanagerd[30673] <Notice>: Target app was terminated; removing process assertion: 30705
Sep 22 14:39:32 iPhonex watchdogd(RunningBoardServices)[57] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex useractivityd(RunningBoardServices)[29803] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex backboardd(RunningBoardServices)[19254] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex wifid(RunningBoardServices)[51] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex runningboardd(RunningBoardServices)[32] <Error>: Unable to get short BSD proc info for 30705: No such process
Sep 22 14:39:32 iPhonex locationd(RunningBoardServices)[26698] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex UserEventAgent(RunningBoardServices)[29] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex CommCenter(RunningBoardServices)[91] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex backboardd(RunningBoardServices)[19254] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex kbd(RunningBoardServices)[517] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex testmanagerd(RunningBoardServices)[30673] <Notice>: Received state update for 30705
Sep 22 14:39:32 iPhonex runningboardd(RunningBoardServices)[32] <Error>: Unable to get short BSD proc info for 30705: No such process
Sep 22 14:39:32 iPhonex runningboardd(RunningBoard)[32] <Error>: RBSStateCapture remove item called for untracked item 32-35-515351 (target:[application<com.happyelements.Sakicn>:30705])
Sep 22 14:39:33 iPhonex ReportCrash[30356] <Notice

https://user-images.githubusercontent.com/56209295/191679147-9f63215c-ed82-4bc3-bbbb-70443d4358b3.mp4
崩溃视频：
>: Formulating fatal 309 report for corpse[30705] saki_apple
