### ISSUE TITLE
[cocos2dx-js sdk 集成]将cocos-2dx-js/poco文件夹拷贝到项目脚本目录，在CocosCreator中编译报错

### ISSUE THREAD

**Issue by DowntonAbbey** [AirtestProject/Poco-SDK#16]
cCcosCreator版本：1.8
报错信息：load script [C:\Users\Administrator\Desktop\AirTest\complete_project\temp\quick-scripts\assets\scripts\Poco\Cocos2dxDumper.js] failed : TypeError: Cannot read property 'prototype' of undefined
    at __define (C:\Users\Administrator\Desktop\AirTest\complete_project\temp\quick-scripts\assets\scripts\Poco\Cocos2dxDumper.js:18:48)
    at C:\Users\Administrator\Desktop\AirTest\complete_project\temp\quick-scripts\assets\scripts\Poco\Cocos2dxDumper.js:42:13
    at Object.<anonymous> (C:\Users\Administrator\Desktop\AirTest\complete_project\temp\quick-scripts\assets\scripts\Poco\Cocos2dxDumper.js:49:11)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\AirTest\complete_project\temp\quick-scripts\assets\scripts\Poco\Cocos2dxDumper.js:52:3)
    at Module._compile  (module.js:571:32)
    at Object.Module._extensions..js  (module.js:580:10)
    at Module.load  (module.js:488:32)
    at tryModuleLoad  (module.js:447:12)
    at Function.Module._load  (module.js:439:3)
    at Module.require  (module.js:498:17

**Comment by adolli** [comment]
是否有将 `sdk/AbstractDumper.js` 放到 `Cocos2dxDumper.js` 之前加载？

**Comment by jef-chen** [comment]
> 是否有将 `sdk/AbstractDumper.js` 放到 `Cocos2dxDumper.js` 之前加载？

我将Poco-SDK放到了我的项目的脚本目录：
```
cp -r <path-to>/Poco-SDK/cocos2dx-js/Poco <my-project>/assets/scripts/poco
```
并修改project.json
```
{
  "engine": "cocos2d-html5",
  "packages": "packages",
  "jsList": [
    "poco/sdk/AbstractDumper.js",
    "poco/sdk/AbstractNode.js",
    "poco/sdk/Attributor.js",
    "poco/sdk/DefaultMatcher.js",
    "poco/sdk/IScreen.js",
    "poco/sdk/Selector.js",
    "poco/Cocos2dxNode.js",
    "poco/Cocos2dxDumper.js",
    "poco/POCO_SDK_VERSION.js",
    "poco/Poco.js"
  ]
}
```
也是同样的报错,请问如何解决？

**Comment by jef-chen** [comment]
window. 的模块引入方式的问题，改成require可以解决~
