### ISSUE TITLE
[cocos-lua Airtest IDE v0.1.4 for MAC]脚本链接不上，怀疑内部脚本写死

### ISSUE THREAD

**Issue by zhuzujie** [AirtestProject/Poco-SDK#22]
这个 wjjn3033不是我的用户名
----------------------------------------------------------------------
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
  File "/Applications/AirtestIDE.app/Contents/MacOS/untitled.air/untitled.py", line 10, in <module>
    poco = StdPoco(15004)
  File "/Users/wjjn3033/dev/idestable/poco/poco/drivers/std/__init__.py", line 77, in __init__
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by adolli** [comment]
此问题在最新版中已修复。另外wjjn3033是打包机的名称，由于脚本是打包到AirtestIDE里的，所以会保留打包机的路径信息，请忽略。
