### ISSUE TITLE
js 无法看到ui树

### ISSUE THREAD

**Issue by brighthead** [AirtestProject/Poco-SDK#55]
AS 里面看log，发现websocketserver 已经启动
2019-10-21 14:10:04.951 4824-4963/com.ygqp.game1 D/cocos2d-x debug info: JS: Cocos2d-JS v3.10
2019-10-21 14:10:04.978 4824-4963/com.ygqp.game1 D/cocos2d-x debug info: try starting wss..
2019-10-21 14:10:04.979 4824-4963/com.ygqp.game1 D/WebSocketServer.cpp: [WebSocketServer::init] _port: 5003 
2019-10-21 14:10:04.979 4824-5109/com.ygqp.game1 D/WebSocketServer.cpp: WebSocketServer thread start, helper instance: 0xca55f1c0
2019-10-21 14:10:04.979 4824-5109/com.ygqp.game1 D/libwebsockets: NOTICE: Initial logging level 1023
2019-10-21 14:10:04.979 4824-5109/com.ygqp.game1 D/libwebsockets: NOTICE: Libwebsockets version: 1.6.0 3ca4bac
2019-10-21 14:10:04.979 4824-5109/com.ygqp.game1 D/libwebsockets: NOTICE: IPV6 compiled in and enabled
2019-10-21 14:10:04.979 4824-5109/com.ygqp.game1 D/libwebsockets: NOTICE: libev support not compiled in
2019-10-21 14:10:04.980 4824-5109/com.ygqp.game1 D/libwebsockets: NOTICE:  mem: platform fd map:  4096 bytes
2019-10-21 14:10:04.980 4824-5109/com.ygqp.game1 D/libwebsockets: NOTICE:  mem: per-conn:          268 bytes + protocol rx buf
2019-10-21 14:10:05.006 4824-4963/com.ygqp.game1 D/cocos2d-x debug info: Network onServerUp...
2019-10-21 14:10:05.006 4824-4963/com.ygqp.game1 D/cocos2d-x debug info: {"type":"serverup"}

现在游戏基于 v3.10开发，好像不支持 require 语句，我加上 require（‘poco’）在 main.js
里面就报错，我把3.10里的websocket都用 3.13的替换了，所以现在可以编译成功，游戏也能跑起来，但到 airetest ide里面poco的 ui树就是无法刷新，log viewer里面报错 invalid select payload，

我现在没有加入 require（‘poco’）别的都是按照教程里面一步一步做的，请问这个如果require 是必须的话，如果 3.10没有支持，如何绕过？

**Comment by yimelia** [comment]
看一下和IDE一起启动的那个黑色命令行窗口里面报的错是什么，截个图看看？

**Comment by brighthead** [comment]
initializing Cocos-js poco.
connecting server..
on error url is invalid
[rpc]closed
[rpc]waiting for connection...0
on close
[rpc]closed
Traceback (most recent call last):
  File "app\plugins\poco\poco_probe.py", line 209, in initPoco
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 30, in wait_connected
    return self.connect()
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 23, in connect
    self._wait_connected(timeout)
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 40, in _wait_connected
    raise RpcConnectionError("Rpc Connection Closed")
poco.utils.simplerpc.simplerpc.RpcConnectionError: Rpc Connection Closed



命令行窗口 报错

**Comment by brighthead** [comment]
Traceback (most recent call last):
  File "app\plugins\poco\poco_probe.py", line 209, in initPoco
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 30, in wait_connected
    return self.connect()
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 23, in connect
    self._wait_connected(timeout)
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 40, in _wait_connected
    raise RpcConnectionError("Rpc Connection Closed")
poco.utils.simplerpc.simplerpc.RpcConnectionError: Rpc Connection Closed
[03:26:12][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-09-10_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s K3V7N19131000043 forward tcp:5003 tcp:5003
[03:26:12][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-09-10_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s K3V7N19131000043 forward --no-rebind tcp:13649 tcp:5003
initializing Cocos-js poco.
connecting server..
[rpc]waiting for connection...0
on error [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[rpc]closed

**Comment by brighthead** [comment]
initializing Cocos-js poco.
connecting server..
on error url is invalid
[rpc]waiting for connection...0
[rpc]closed
on close
[rpc]closed
Traceback (most recent call last):
  File "app\plugins\poco\poco_probe.py", line 209, in initPoco
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 30, in wait_connected
    return self.connect()
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 23, in connect
    self._wait_connected(timeout)
  File "D:\AirtestIDE_2019-09-10_py3_win64\poco\utils\simplerpc\rpcclient.py", line 40, in _wait_connected
    raise RpcConnectionError("Rpc Connection Closed")
poco.utils.simplerpc.simplerpc.RpcConnectionError: Rpc Connection Closed
[03:44:14][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-09-10_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s K3V7N19131000043 forward tcp:5037 tcp:5003
Traceback (most recent call last):
  File "app\plugins\poco\poco_probe.py", line 195, in initPoco
  File "airtest\core\android\adb.py", line 459, in forward
    self.cmd(cmds + [local, remote])
  File "airtest\core\android\adb.py", line 187, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[] stderr[error: internal error

**Comment by yimelia** [comment]
connecting server..
on error url is invalid
这个log是你们游戏打出来的么？

**Comment by brighthead** [comment]
airtest命令行窗口打印出来的

**Comment by brighthead** [comment]
是我3.10无法支持你们js版本提供的sdk，我关掉这个issue了
