### ISSUE TITLE
识别不到cocos2dx-lua 游戏中的UI元素

### ISSUE THREAD

**Issue by sosocgx** [AirtestProject/Poco-SDK#7]
有一些问题请教：

1.尝试集成了pocosdk之后，提示找不到version.
在POCO_SDK_VERSION.lua硬写入 local VERSION = "1.0.1"--import('.POCO_SDK_VERSION')
打包成功。
2.集成以后如何确定是否集成成功？
3.在Airtest IDE或者 PocoHierarchyViewer中， 都没有识别cocos2dx-lua的选项， 如何识别UI元素？

**Comment by adolli** [comment]
请在此[下载](http://airtest.netease.com/)最新AirtestIDE，hierarchy窗格中选cocos2dx-lua，如果能刷出来表示集成成功，如果不能请看下console窗口里有无报错信息。如果有报错信息麻烦贴一下这里。

本周还会继续完善配套工具。

**Comment by sosocgx** [comment]
更新了IDE到最新，可以看到cocos-lua选项， 启动游戏后识别会报错，截图如下
<img width="437" alt="20180412133720" src="https://user-images.githubusercontent.com/929831/38658586-61b0cdcc-3e58-11e8-94f1-d66bc0c72cd0.png">

**Comment by adolli** [comment]
请尝试重新clone此仓库代码更新一下sdk，如果仍然报错，麻烦告知一些你的cocos2dx版本号以及使用的开发工具(cocosstudio / cocosbuilder /...)。
另外可以安装了poco后尝试直接在python中运行以下代码看下有何报错

```bash
pip install pocoui
```

```python
from airtest.core.api import connect_device
from poco.drivers.std import StdPoco

connect_device('Android:///')
poco = StdPoco(10054)
for n in poco():
    print n.get_name()
```

**Comment by adolli** [comment]
请不要在IDE里运行，直接 `python untitled.air/untitled.py`

**Comment by sosocgx** [comment]
这个是在终端运行的结果
sudo python /Users/cgx/Desktop/test.py 
Password:
[02:12:10][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb devices
Traceback (most recent call last):
  File "/Users/cgx/Desktop/test.py", line 4, in <module>
    connect_device('Android:///')
  File "/Library/Python/2.7/site-packages/airtest/core/api.py", line 46, in connect_device
    dev = cls(uuid, **params)
  File "/Library/Python/2.7/site-packages/airtest/core/android/android.py", line 29, in __init__
    self.serialno = serialno or ADB().devices(state="device")[0][0]
  File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 196, in devices
    output = self.cmd("devices", device=False)
  File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 167, in cmd
    proc = self.start_cmd(cmds, device)
  File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 146, in start_cmd
    stderr=subprocess.PIPE
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
exiting.......

**Comment by adolli** [comment]
抱歉，端口号我写错了，是15004不是10054

**Comment by adolli** [comment]
另外好像你的mac上是不是之前装过adb，试试
```
adb version
adb devices
```
有何输出

**Comment by sosocgx** [comment]
adb version
Android Debug Bridge version 1.0.32
 adb devices
adb server is out of date.  killing...
* daemon started successfully *
List of devices attached 
3418b8e1	device


端口改了，重新执行，是一样的报错

[DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb devices
Traceback (most recent call last):
File "/Users/cgx/Desktop/test.py", line 4, in 
connect_device('Android:///')
File "/Library/Python/2.7/site-packages/airtest/core/api.py", line 46, in connect_device
dev = cls(uuid, **params)
File "/Library/Python/2.7/site-packages/airtest/core/android/android.py", line 29, in init
self.serialno = serialno or ADB().devices(state="device")[0][0]
File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 196, in devices
output = self.cmd("devices", device=False)
File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 167, in cmd
proc = self.start_cmd(cmds, device)
File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 146, in start_cmd
stderr=subprocess.PIPE
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
OSError: [Errno 13] Permission denied
exiting.......

**Comment by sosocgx** [comment]
Permission denied的问题我自己解决了，现在使用您的脚本还是报错，麻烦看一下

sudo python /Users/cgx/Desktop/test.py  
[04:01:39][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb devices
[04:01:39][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 wait-for-device
[04:01:39][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 shell getprop ro.build.version.sdk
[04:01:39][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 shell netcfg
[04:01:39][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 shell ifconfig
Connecting to host at: (u'172.16.142.232', 15004)
waiting for connection...0
error: uncaptured python exception, closing channel <poco.utils.simplerpc.transport.tcp.asynctcp.Client 172.16.142.232:15004 at 0x116d32fc8> (<class 'socket.error'>:[Errno 61] Connection refused [/Library/Python/2.7/site-packages/poco/utils/simplerpc/transport/tcp/asyncore.py|read|83] [/Library/Python/2.7/site-packages/poco/utils/simplerpc/transport/tcp/asyncore.py|handle_read_event|446] [/Library/Python/2.7/site-packages/poco/utils/simplerpc/transport/tcp/asyncore.py|handle_connect_event|454])
Closed <poco.utils.simplerpc.transport.tcp.asynctcp.Client 172.16.142.232:15004 at 0x116d32fc8>
waiting for connection...1
Traceback (most recent call last):
  File "/Users/cgx/Desktop/test.py", line 5, in <module>
    poco = StdPoco(15004)
  File "/Library/Python/2.7/site-packages/poco/drivers/std/__init__.py", line 92, in __init__
    agent = StdPocoAgent((ip, port))
  File "/Library/Python/2.7/site-packages/poco/drivers/std/__init__.py", line 69, in __init__
    self.c.wait_connected()
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/rpcclient.py", line 57, in wait_connected
    raise RuntimeError("Connection Closed")
RuntimeError: Connection Closed
exiting.......
<LoopThread(simplerpc_update, started daemon 123145482825728)> finished

**Comment by adolli** [comment]
你用的是模拟器吗？我看设备在172.16的网段上，不知道是不是不能访问这个网络

**Comment by sosocgx** [comment]
不是我用的是安卓设备。 172.16.142.232这个是我设备的IP

**Comment by adolli** [comment]
试下`pip install -U pocoui`后在重跑下，修了一些网的问题。

**Comment by sosocgx** [comment]
重跑的报错：
➜  ~ sudo python /Users/cgx/Desktop/test.py 
[06:26:09][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb devices
[06:26:09][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 wait-for-device
[06:26:09][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 shell getprop ro.build.version.sdk
[06:26:09][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 forward --no-rebind tcp:19395 tcp:15004
Connecting to host at: ('localhost', 19395)
<poco.utils.simplerpc.transport.tcp.asynctcp.Client localhost:19395 at 0x116c62ef0> is connected
waiting for connection...0
Closed <poco.utils.simplerpc.transport.tcp.asynctcp.Client localhost:19395 at 0x116c62ef0>
Traceback (most recent call last):
  File "/Users/cgx/Desktop/test.py", line 6, in <module>
    poco("Button_bag").click()
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 21, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 280, in click
    pos_in_percentage = self.get_position(focus)
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 404, in get_position
    pos = self.attr('pos')
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 37, in wrapped
    return func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 524, in attr
    nodes = self._do_query(multiple=False)
  File "/Library/Python/2.7/site-packages/poco/proxy.py", line 653, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Library/Python/2.7/site-packages/poco/freezeui/hierarchy.py", line 89, in select
    return self.selector.select(query, multiple)
  File "/Library/Python/2.7/site-packages/poco/sdk/Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "/Library/Python/2.7/site-packages/poco/sdk/Selector.py", line 70, in getRoot
    return self.dumper.getRoot()
  File "/Library/Python/2.7/site-packages/poco/freezeui/hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "/Library/Python/2.7/site-packages/poco/utils/simplerpc/simplerpc.py", line 75, in wait
    raise RuntimeError("%s timeout error" % self)
RuntimeError: <poco.utils.simplerpc.simplerpc.Callback object at 0x116d715d0> timeout error
exiting.......
[06:26:39][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s 3418b8e1 forward --remove tcp:19395
<LoopThread(simplerpc_update, started daemon 123145333555200)> finished

**Comment by adolli** [comment]
这个像是游戏端的问题了，你在logcat里能看到lua报的错吗？

**Comment by adolli** [comment]
你确认一下`script/poco/POCO_SDK_VERSION.lua`这个文件到底在不在，如果是文件名识别问题的话，你先手动在`poco_manager.lua`里填上VERSION的值再试下。

**Comment by adolli** [comment]
另外也可以下载这个apk装上去试一下[cocos2dx-lua sdk test](http://top.gdl.netease.com/poco-res/poco-sdk-test-cocos2dx-lua-demo-android.zip)，排除手机和网络问题。

**Comment by sosocgx** [comment]
目录下有version文件，如硬写入写入版本号
在POCO_SDK_VERSION.lua硬写入 local VERSION = "1.0.1"--import('.POCO_SDK_VERSION')
，最会想我最开始回复的一样报错
<img width="789" alt="20180413193805" src="https://user-images.githubusercontent.com/929831/38732838-55880600-3f52-11e8-8e37-9dbd6e16d0db.png">

**Comment by adolli** [comment]
你很有可能是遇到了这个问题 https://stackoverflow.com/a/33842352

**Comment by adolli** [comment]
你很有可能是遇到了这个问题 https://stackoverflow.com/a/33842352

如果你们引擎解决不了，那就把Cocos2dxNode.lua的这几行代码删掉
https://github.com/AirtestProject/Poco-SDK/blob/master/cocos2dx-lua/poco/Cocos2dxNode.lua#L168-L172

**Comment by sosocgx** [comment]
非常感谢您的耐心解决，现在简单的调试已经可以跑起来了。不过目前IDE识别时有些不太好用，会出现卡死，和识别不到的情况。不过应该可以通过cocosstudio 直接去找对应的UI 。
