### ISSUE TITLE
cocos-lua可以识别出控件，但是脚本无法运行

### ISSUE THREAD

**Issue by Annxui** [AirtestProject/Poco-SDK#8]
from poco.drivers.std import StdPoco
poco = StdPoco()
poco("Button_bag").click()
-----------------------------------------------------------------------------------------------
> [Start running..]
> [02:20:36][DEBUG]<airtest.core.android.adb> E:\Airtest\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 42f64a0baa5cbf51 wait-for-device
> [02:20:36][DEBUG]<airtest.core.android.adb> E:\Airtest\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 42f64a0baa5cbf51 shell getprop ro.build.version.sdk
> [02:20:36][DEBUG]<airtest.utils.logwraper> main_script: {'script': u'E:\\rok_Script\\untitled.air'}
> [02:20:36][DEBUG]<airtest.core.android.adb> E:\Airtest\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 42f64a0baa5cbf51 shell netcfg ; echo ---$?---
==================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 84, in runTest
  File "E:\untitled.air\untitled.py", line 11, in <module>
    poco("Button_bag").click()
  File "poco\proxy.py", line 21, in wrapped
  File "poco\proxy.py", line 280, in click
  File "poco\proxy.py", line 404, in get_position
  File "poco\proxy.py", line 37, in wrapped
  File "poco\proxy.py", line 524, in attr
  File "poco\proxy.py", line 653, in _do_query
  File "poco\freezeui\hierarchy.py", line 89, in select
  File "poco\sdk\Selector.py", line 77, in select
  File "poco\sdk\Selector.py", line 70, in getRoot
  File "poco\freezeui\hierarchy.py", line 35, in getRoot
  File "poco\utils\simplerpc\utils.py", line 13, in new_func
  File "poco\utils\simplerpc\simplerpc.py", line 75, in wait
RuntimeError: <poco.utils.simplerpc.simplerpc.Callback object at 0x000000000472CE10> timeout error

**Comment by adolli** [comment]
请尝试重新clone此仓库代码更新一下sdk，如果仍然报错，请安装poco后尝试直接在python中运行下面代
码。
```bash
pip install pocoui
```

```python
from airtest.core.api import connect_device
from poco.drivers.std import StdPoco

connect_device('Android:///')
poco = StdPoco()
poco("Button_bag").click()
```

**Comment by Annxui** [comment]
更新SDK后问题解决，感谢！！！
